//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alela.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public string Name { get; set; }
        public string Culture { get; set; }
        public bool IsSystem { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public int ID { get; set; }
    }
}
